# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacktrack', '0002_auto_20170108_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
