# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stacktrack', '0003_delete_greeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(default='')),
                ('precious_metal', models.CharField(choices=[('Ag', 'Silver'), ('Au', 'Gold'), ('Pt', 'Platinum'), ('Pd', 'Palladium'), ('Rh', 'Rhodium'), ('Cu', 'Copper')], default='Ag', max_length=2)),
                ('fineness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacktrack.Fineness')),
            ],
        ),
        migrations.CreateModel(
            name='IngotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('plural', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.FloatField(default=31.1)),
                ('friendly_name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'weights',
            },
        ),
        migrations.AddField(
            model_name='ingot',
            name='ingot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacktrack.IngotType'),
        ),
        migrations.AddField(
            model_name='ingot',
            name='mass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacktrack.Mass'),
        ),
    ]
